//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AnyID.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataContext object using the connection string found in the 'DataContext' section of the application configuration file.
        /// </summary>
        public DataContext() : base("name=DataContext", "DataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataContext object.
        /// </summary>
        public DataContext(string connectionString) : base(connectionString, "DataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataContext object.
        /// </summary>
        public DataContext(EntityConnection connection) : base(connection, "DataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<B_VIEW_GAM> B_VIEW_GAM
        {
            get
            {
                if ((_B_VIEW_GAM == null))
                {
                    _B_VIEW_GAM = base.CreateObjectSet<B_VIEW_GAM>("B_VIEW_GAM");
                }
                return _B_VIEW_GAM;
            }
        }
        private ObjectSet<B_VIEW_GAM> _B_VIEW_GAM;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the B_VIEW_GAM EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToB_VIEW_GAM(B_VIEW_GAM b_VIEW_GAM)
        {
            base.AddObject("B_VIEW_GAM", b_VIEW_GAM);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="B_VIEW_GAM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_VIEW_GAM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new B_VIEW_GAM object.
        /// </summary>
        /// <param name="aCID">Initial value of the ACID property.</param>
        public static B_VIEW_GAM CreateB_VIEW_GAM(global::System.String aCID)
        {
            B_VIEW_GAM b_VIEW_GAM = new B_VIEW_GAM();
            b_VIEW_GAM.ACID = aCID;
            return b_VIEW_GAM;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ACID
        {
            get
            {
                return _ACID;
            }
            set
            {
                if (_ACID != value)
                {
                    OnACIDChanging(value);
                    ReportPropertyChanging("ACID");
                    _ACID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ACID");
                    OnACIDChanged();
                }
            }
        }
        private global::System.String _ACID;
        partial void OnACIDChanging(global::System.String value);
        partial void OnACIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOL_ID
        {
            get
            {
                return _SOL_ID;
            }
            set
            {
                OnSOL_IDChanging(value);
                ReportPropertyChanging("SOL_ID");
                _SOL_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOL_ID");
                OnSOL_IDChanged();
            }
        }
        private global::System.String _SOL_ID;
        partial void OnSOL_IDChanging(global::System.String value);
        partial void OnSOL_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FORACID
        {
            get
            {
                return _FORACID;
            }
            set
            {
                OnFORACIDChanging(value);
                ReportPropertyChanging("FORACID");
                _FORACID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FORACID");
                OnFORACIDChanged();
            }
        }
        private global::System.String _FORACID;
        partial void OnFORACIDChanging(global::System.String value);
        partial void OnFORACIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACCT_NAME
        {
            get
            {
                return _ACCT_NAME;
            }
            set
            {
                OnACCT_NAMEChanging(value);
                ReportPropertyChanging("ACCT_NAME");
                _ACCT_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACCT_NAME");
                OnACCT_NAMEChanged();
            }
        }
        private global::System.String _ACCT_NAME;
        partial void OnACCT_NAMEChanging(global::System.String value);
        partial void OnACCT_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SCHM_CODE
        {
            get
            {
                return _SCHM_CODE;
            }
            set
            {
                OnSCHM_CODEChanging(value);
                ReportPropertyChanging("SCHM_CODE");
                _SCHM_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SCHM_CODE");
                OnSCHM_CODEChanged();
            }
        }
        private global::System.String _SCHM_CODE;
        partial void OnSCHM_CODEChanging(global::System.String value);
        partial void OnSCHM_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CLR_BAL_AMT
        {
            get
            {
                return _CLR_BAL_AMT;
            }
            set
            {
                OnCLR_BAL_AMTChanging(value);
                ReportPropertyChanging("CLR_BAL_AMT");
                _CLR_BAL_AMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLR_BAL_AMT");
                OnCLR_BAL_AMTChanged();
            }
        }
        private Nullable<global::System.Decimal> _CLR_BAL_AMT;
        partial void OnCLR_BAL_AMTChanging(Nullable<global::System.Decimal> value);
        partial void OnCLR_BAL_AMTChanged();

        #endregion

    
    }

    #endregion

    
}
